### ISSUE TITLE
boxo: a library/toolbox for building IPFS applications and implementations in Go

### ISSUE THREAD

**Issue by reidlw** [ipfs/roadmap#107]
eta: 2023-06-30

description:
Core Kubo functionality is refactored into a library used both by Kubo as well as other implementers who want to support additional use cases without blocking on Kubo maintainers.

Kubo has a bunch of battle-tested code over the years. Unfortunately it’s not easy to consume as a library because of the repo sprawl and having to pull in all the relevant pieces. It’s also hard for maintainers to keep it updated and we’re reliant on Kubo as the delivery vehicle to specify compatible versions. Seeing the success go-libp2p has had moving to a monorepo, we will move to a similar pattern where Kubo specifics stay in Kubo but the generally usable parts for anyone writing an IPFS implementation in Go can live in libipfs

Done: Core Kubo functionality is packaged into a library used both by Kubo as well as other implementers who want to support additional use cases without blocking on Kubo maintainers

**Comment by BigLep** [comment]
Actual work tracking is happening in https://github.com/ipfs/boxo/issues/196

**Comment by momack2** [comment]
@BigLep would you consider this milestone "done"? If not, can you choose a new launch date for the considered "Ready" state?

**Comment by BigLep** [comment]
@momack2 : https://github.com/ipfs/boxo/issues/196 is the item that should be completed to call this done-done-done.  

I have adjusted the "eta" to 2023-04-28 from 2023-03-30.

**Comment by quickhatche** [comment]
@BigLep Checking in on this milestone to see if it is also done or needs to be pushed out as well

**Comment by BigLep** [comment]
@quickhatche : https://github.com/ipfs/boxo/issues/196 isn't fully done, but we're working to complete it this week.  I'll update the ETA.  Thanks.

**Comment by quickhatche** [comment]
Gentle nudge on this @BigLep to see if the ETA can be updated esp if still in progress.

**Comment by BigLep** [comment]
@quickhatche : I have updated the date to be end of month since we're still resolving issues with https://github.com/ipfs/boxo/issues/196

**Comment by BigLep** [comment]
This was completed 2023-06-30 with https://github.com/ipfs/boxo/issues/196
