### ISSUE TITLE
Indexer double hashing support

### ISSUE THREAD

**Issue by reidlw** [ipfs/roadmap#108]
eta: 2023-03-31

description:
Define and deliver support for double hashing with indexers from Kubo to enhance IPFS privacy.

Shared effort with Probelab, Bedrock, and libp2p.

**Comment by quickhatche** [comment]
Hello @wilkyr31d ! Checking in on the status of this - ETA shows end of Q1, should this be marked as done or status needs to be updated?

**Comment by quickhatche** [comment]
@BigLep Do you know if this milestone is completed?

**Comment by BigLep** [comment]
@quickhatche : this issue is stale.  A replacement issue that covers the "Kubo reader privacy" story is here: https://github.com/ipfs/kubo/issues/9818

I'm going to close this.
