### ISSUE TITLE
PL EngRes IPFS Stewards / IPFS-in-JS Roadmap

### ISSUE THREAD

**Issue by TinyTb** [ipfs/roadmap#113]
"Pomegranate" is the temporary codename for the new IPFS implementation in JavaScript which will be developed starting in late 2022.

For a link to the Roadmap, and a place to share comments, see:
- https://github.com/ipfs/pomegranate/issues/5

**Comment by BigLep** [comment]
@tinytb : given we have https://github.com/ipfs/pomegranate/issues/5, I think we can close this issue.

When https://github.com/ipfs/roadmap/issues/94 is done, we'll have links to relevant roadmaps.

**Comment by TinyTb** [comment]
As mentioned, when available, the roadmap will be discoverable via https://github.com/ipfs/pomegranate/issues/5
