### ISSUE TITLE
Tackle tracking protection 

### ISSUE THREAD

**Issue by Gozala** [ipfs/roadmap#15]
As conventional web become more popular, advertisers realized it could be a perfect vehicle for their business. Today we're tracked through the web to drive that business. Some browser vendors are putting a lot of effort against trackers. As I understand use of DHTs makes tracking even easier and as IPFS gets more popular it would attract same actors. Furthermore it creates a huge risk to people leaving under censorship as through tracking prosecutors will be gain ability to discover people accessing censored content.

Maybe evaluating papers that attempt to solve this e.g. [Octopus: A Secure and Anonymous DHT Lookup](https://arxiv.org/abs/1203.2668) would be a worthy goal for the roadmap.

**Comment by Gozala** [comment]
I should also mention that in personal conversations this comes up a lot as a reason for skepticism from browser implementers.

**Comment by momack2** [comment]
Thanks for the comment, Iralki! On the IPFS side, we're tracking privacy-related work in our 2020 goal for "[the Encrypted Web](https://github.com/ipfs/roadmap#-encrypted-web-d2-e3-i4)" - but most of the work on something like you describe would be in [Libp2p](https://libp2p.io). I hear there _might_ be some progress on the DHT work in 2019 on the [Libp2p roadmap](https://github.com/libp2p/libp2p/issues/60) (bulletproof DHTs and/or private transports), so I'd encourage you to join the conversation there.

**Comment by Gozala** [comment]
@momack2 would you mind migrate this issue there (I believe github added support for that now, but requires privileges to do so)

**Comment by momack2** [comment]
@daviddias - do you have this capability? I do not.

**Comment by daviddias** [comment]
I'm able to move issues between repos inside the same org. I guess I could work around it by moving the libp2p repo to this org, moving the issue and then moving back the repo, but to avoid doing something on the beta beta features of github, what about just reopening it?

**Comment by Gozala** [comment]
@daviddias yeah that sounds complicated, I’ll just open one thete

**Comment by daviddias** [comment]
thank you @Gozala :) post here the url for it when you have created

**Comment by Gozala** [comment]
https://github.com/libp2p/libp2p/issues/67
