### ISSUE TITLE
Exercise: Allocating WG Roadmap Milestones by Quarter

### ISSUE THREAD

**Issue by momack2** [ipfs/roadmap#17]
Hello IPFS WGs - @ipfs/wg-captains, @ipfs/contributors! 
We’re trying to **solidify [Q1 OKRs](https://docs.google.com/spreadsheets/d/1BtOfd7s9oYO5iKsIorCpsm4QuQoIsoZzSz7GItE-9ys/edit#gid=1681757723) by end of next week (1/18)**! Now that we have defined our goals for 2019 in this repo, we are excited to start using our [2019 Working Group Roadmaps](https://github.com/ipfs/roadmap/pulls) to gain perspective and confidence that our quarterly efforts put us on track to meet our yearly objectives. To help us do this, the Project Working Group prototyped and refined a short *~15-25 minute* exercise that we encourage all working groups to do (either sync or async) as a quick feedback mechanism for our [Q1 OKRs](https://docs.google.com/spreadsheets/d/1BtOfd7s9oYO5iKsIorCpsm4QuQoIsoZzSz7GItE-9ys/edit#gid=1681757723). As a benefit - it helps us tighten up our [2019 Working Group Roadmaps](https://github.com/ipfs/roadmap/pulls) and make them more actionable and informative for the wider community. 🎉

## The exercise:
- **Step 1 (1 min):** Divide milestones amongst team members - either with small groups owning sets of milestones (ex “Package Managers”, “Large Files”, “Production Ready”), or individuals taking ownership of specific milestones.
- **Step 2 (5-10 mins):** Within Github, a Google Doc, or a Cryptpad - team members assign each milestone a quarter, or, if the milestone will span multiple quarters of work, break the milestone down into sequential “Parts 1, 2, 3” of work that are each assigned a quarter. In addition, team members give a rhetoric for **_why_** that quarter (either with a quick verbal explanation, or by writing a comment - ex, “I think we need to do benchmarking this quarter so we can prioritize among improvements to X the next quarter”).
- **Step 3 (1-5 min):** Rearrange milestones and parts into the [“Timeline” section](https://github.com/ipfs/roadmap/pull/2/files#diff-1cd135787ea35ac66b6f0f1ba6cddea7R84) of each WG Roadmap by quarter and look at the distribution of work. Modify and iterate as needed to make sure one quarter in particular isn’t overloaded with too many large commitments for specific resources.
- **Step 4 (5-10 mins):** Look back at your [Q1 OKRs](https://docs.google.com/spreadsheets/d/1BtOfd7s9oYO5iKsIorCpsm4QuQoIsoZzSz7GItE-9ys/edit#gid=1681757723) - do your key results align with the work described in the Q1 section of your 2019 roadmap? If not, reflect on what work is important to prioritize this quarter to most efficiently reach our 2019 goals (ex through accomplishing prerequisites, accelerating development, simplifying maintenance, or utilizing ecosystem effects) and add/remove KRs accordingly.

## What we did in our Project WG meeting:
- We allocated 1 project wg member per 2019 priority area and spent 5 minutes silently doing steps 2 & 3 (could have easily been done async).
- We then took an additional ~15 minutes of our meeting to walk through each milestone and let each individual explain their rhetoric (ex past/future dependencies, ecosystem effects, etc). As a group, we moved a few milestones around based on load distribution and other comments.
- (WIP) Async, we compared our Q1 milestones and Q1 OKRs to note discrepancies and ensure our goals put us on track for future quarters.
_Want to see it in action? Watch [the recording of our meeting](https://drive.google.com/file/d/1zzgkpgC_2s5H6yCZs8vY4XU-pDAJLPtt/view)! Feel free to zoom through our 5 mins of silence where we did steps 2&3 async or just [watch us talk through an example](https://drive.google.com/file/d/1zzgkpgC_2s5H6yCZs8vY4XU-pDAJLPtt/view?t=431). ;)_

## Goals and benefits:
1. Waiting to chart the quarter until we're doing that quarter's OKRs can easily cause us to run out of time to handle important tasks by not starting early enough. If we take a stab at allocating our quarters out right now, we can try and rebalance (and proactively readjust quarters that seem overloaded) to make sure we get the most important work accomplished.
2. Assigning milestones a quarter estimate helps community members understand when to interface with us on a particular effort on our 2019 roadmap.
3. Our dependencies (chunks of work that build on each other) get more clearly defined by charting incremental work across quarters - and it helps us ensure we’ll have time to complete dependencies before the efforts that depend on them.
4. In addition to “priority”, thinking about allocating milestones in time helps us proactively prioritize items that we expect to accelerate our development or create ecosystem effects within our community.

Excited to see how this helps other WGs get clarity and excitement for what we plan to accomplish this quarter! And pumped to get all these awesome PRs merged. =]

**Comment by daviddias** [comment]
As a good pratice, the Project WG also allocated support DRI to help each Working Group finalize this last round of planning. The DRIs for each Working Group are:

- JavaScript Core Dev (@daviddias)
- Golang Core Dev (@momack2)
- IPFS GUI (@daviddias)
- IPFS Cluster (@meiqimichelle)
- IPFS Infrastructure (@momack2)
- Integration with Web Browsers (@olizilla)
- Dynamic Data and Capabilities (@daviddias)
- Decentralized Data Stewardship (@meiqimichelle)
- Local Offline Collaboration (@momack2)
- Project (@daviddias)
- Community (@parkan)

Expect to get a ping from your Support DRI, meanwhile you can get to exercise ^^.
