### ISSUE TITLE
[2020 Theme Proposal] Wikipedia Mirror: Improving Access to World’s Knowledge

### ISSUE THREAD

**Issue by lidel** [ipfs/roadmap#46]
_Note, this is part of the [2020 Theme Proposals Process](https://github.com/ipfs/roadmap/blob/master/2020-IPFS-Project-Planning.md) - feel free to create additional/alternate proposals, or discuss this one in the comments!_

## Theme description

_Please describe the theme and what it means for the IPFS Project._

In 2020, IPFS **demonstrates its value in a tangible way** that can be understood by *everyone*, not only highly technical people.

Behind the scenes we continue work started in 2019 for package managers, reliability and testing, but we are more vocal about solving real-world problems of people in semi-offline environments prone to network failures or censorship using **[Distributed Wikipedia Mirror](https://github.com/ipfs/distributed-wikipedia-mirror/) project as our North Star**.

We are much better at communicating "why" IPFS, and make sure it is followed by a clear "how". 

## Core needs & gaps
_Please describe in more detail what needs or gaps in our current state this theme addresses, and how it will create value for the IPFS ecosystem._

- We are shipping low level tooling, but it is difficult to pick one and tell a compeling story about it. (ex: a very small number of people maintains package managers and understands how IPFS benefits them)

- User experience around contributing disk space to websites/datasets is lacking, as demonstrated by recent Pinset UX research

- We are not dogfooding enough. Focusing on  wikipedia will act as a forcing function: A big dataset that surfaces real issues, and also opens opportunities. For example, we can demonstrate the power of built-in deduplication and IPLD for a real world use-case by researching feasibility of a custom chunker for the ZIM format.

## Why focus this year

_Please provide rhetoric for why this theme deserves focus in **2020 in particular.**_

- Focusing on package managers and performance issues caused by the sudden growth (DHT, IPNS) raised some healthy skepticism in and outside of our community. People were unsure of the value IPFS brings and we lost some good will along the way.

- We will work on and solve technical issues, but we won't change people's minds with that alone. 

- Having a north star of Distributed Wikipedia improves morale and ensures we focus on the right things. 

- We have a very good story "why IPFS" that basically tells itself to a broad spectrum of internet user. Even end-users who do not understand the specific value of offline access, censorship resistance, etc, will understand "Install this to help others access Wikipedia".

## Milestones & rough roadmap

_Please list relevant development milestones and the high-level timeline for these efforts._

1. Infrastructure
   - Creation of snapshots is automated and verifiable
   - Expanded coverage of languages mirrored on IPFS
   - Storage capacity and related infra is set up
2. Testing / benchmarks
   - Testing is automated and integrated into our project-level CI
   - We see regressions related to real world scenarios such as distributed wikipedia
3. Productization
   - World class design of end-user experience for collaborative cohosting by regular Wikipedia users
   - Collaborative clusters for more technical users with a lot of storage
   - Filecoin integration testcase for crossover project testing and promotion

## Desired / expected impact

- IPFS mirror becomes the default go-to if access to regular Wikipedia is not possible (classrooms in bad/metered networks, censorship, offline networks).
- **People are proud to contribute to the IPFS project.**
- Core team stays motivated around a north star.
- Improved excitement and engagement about IPFS project in the community 
  - People are curious and want to learn about IPFS and contribute to the project 
  - We see more first-time contributors
  - We see increased press coverage

**Comment by lidel** [comment]
_Digression:_

Just to be very clear, the idea is to use Distributed Wikipedia Mirror project as our _north star_ for 2020. Continues on current path, solving similar problems as we did with package managers, but tells a much more compelling story.

When I wrote initial version of this theme proposal it had a big overlap growth-wise with [Solid foundation for future growth](https://github.com/ipfs/roadmap/issues/42), so i simplified it and kept text mostly around Wikipedia Mirror.

I believe this north star could be added to that (or similar) proposal to make it easier to communicate our goals.

**Comment by momack2** [comment]
I agree with the assessment that while package managers are useful for focusing our visibility into core performance challenges that are often common across these use cases, Wikipedia (or the Internet Archive digital archives) are a much more charismatic use case for the general public. “Data package managers” like these demonstrate and highlight many of the performance and usability improvements we’ve worked on in 2019, while continuing to focus work on ensuring ipfs handles use cases reliably at scale for humanity’s critical data and tools. Many of these tools are built in code and hosted in package managers (and we should persist, version, and make available all these useful tools on the dweb), but the content hosted _within_ the tools also needs to be backed up and versioned, so it’s a clear need to complete this work stream. 👍
