### ISSUE TITLE
Dedicated hardware, The back-end service and user front-end

### ISSUE THREAD

**Issue by liyunzhi-666** [ipfs/roadmap#48]
_Note, this is part of the [2020 Theme Proposals Process](https://github.com/ipfs/roadmap/blob/master/2020-IPFS-Project-Planning.md) - feel free to create additional/alternate proposals, or discuss this one in the comments!_
## Theme description
_So far, all the new ecology has the support of new hardware, whether it is the server in the Internet era, the computer or the cloud server in the mobile Internet era or the mobile phone. IPFS, based on the hardware construction of the
 previous era, cannot solve the problem of decentralization, just as more than 60 percent of the current bitcoin and ether mining machines operate in the central machine room.
The first step is decentralisation of hardware, the local application of edge computing force,just  as the blackberry once keep communication networks open in the wake of the September 11th attacks._

## Core needs & gaps
_We need proprietary hardware to ensure our services, and it serves that mission from the day it's made, just like AI chips. The biggest problem is the guarantee of the revenue of these hardware, which must be built into a relatively complete 
revenue model, or integrated it into a complete commercial system to undertake the most basic services.
What's more urgent now is the support of the user's front-end hardware. Just like if without the iphone, the era of smart phones may be delayed for several more years. It is difficult to imagine what effect can be achieved under this compromise,
 since the existing client is based on centralized design both in auditing standards and presentation._

## Why focus this year
_There will be a massive IPFS rollout in 2020, and no doubt that the absence of hardware will make the explosion disjointed and uninspiring enough to encourage fans to invest their energy and money to the project.
If a blackberry-like application is going to ignite the world, Strings of code hidden in the machine can not do this._

## Milestones & rough roadmap
_Core engineering milestone
* the first completely decentralized hardware born
* operate normally without the support of traditional hardware network in extreme environment
* with current hardware and network can be accessed or stripped_

## Desired / expected impact
_Core implementation impact
* minimize the dependence on traditional hardware and networks
* niche applications
* wearable devices for the Internet of things as a breakthrough
_

**Comment by momack2** [comment]
Thanks for the suggestion, @liyunzhi-666! I know the Filecoin team has been thinking about hardware specs for incentivizing distributed storage mining, but that is a separate layer from the IPFS network which would run on top of many potential storage systems (altruistic, collaborative, or incentivized). I don’t understand what you mean by decentralized hardware in the IPFS context - can you expand on what you’re proposing the community should build?

**Comment by liyunzhi-666** [comment]
> 感谢您的建议@ liyunzhi-666！我知道Filecoin团队一直在考虑激励分布式存储挖掘的硬件规格，但这是与IPFS网络分离的一层，该IPFS网络可以运行在许多潜在的存储系统（利他，协作或激励）之上。我不明白您在IPFS上下文中使用分散式硬件的意思-您可以扩展提议的社区应该构建的内容吗？

Perhaps becaus of different point of view, A system that is compatible with mainstream hardware is a good system, but not a great one.
Proprietary hardware on the user front-end (such as the iphone) is essential if the ultimate experience be considered.
The blackberry, for example, it would not have become a mainstream phone had it not been for its ability to communicate reliably during the collapse of the universal messaging network. Of course, due to the use of a large number of traditional mobile phone us, resulting in the popularization of demand, when it chooses to become the same as the android phone, that is, when it disappeared, its positioning should be more similar to the three-defense phone, special phone, rather than arcade.
If the final choice of Filecoin system compatible with the traditional various types of network and hardware and above the various systems, it is questionable whether its own characteristics can be shown. Will it be a short-lived system?
Perhaps it is too early to consider this problem, after all, the system has not come out.There are two ways to become systems, one is like android, all of this are open source, core application commercialization, others is like apple, creating a combination of hardware and software, core application is also commercial and other applications charge service fees.
Maybe there are the third way that we can’t see it, we hope it will be clear in the official roadmap in 2020, rather than just a token. building a global efficient store is not just technically feasible,there are so much work to do.
