### ISSUE TITLE
Upgrading the IPFS Mission Statement

### ISSUE THREAD

**Issue by momack2** [ipfs/roadmap#52]
Last week, we had a short brainstorm session ([meeting notes and outcomes here](https://docs.google.com/document/d/1lE1bzlMj4wwcq5DtatDiUobLG5d_kC_e1XpBi-XXAuE/edit#)) on how we could improve the current IPFS mission statement to be more pithy, visionary, and aligning for the project. We'd like to share what we have so far, and get some ideas/suggestions from others in the community.

## Current Mission
> In order to:
> - Ensure that all people have the ability to efficiently access and grow humanity's knowledge.
> - Mindfully develop new technologies that preserve and promote rights of individuals.
> - Support a persistent, upgradable, and open internet.
> 
> We believe that:
> _All information on the internet should be uniquely and permanently content-addressed on a distributed peer-to-peer web._

## Goal
A one-sentence, action-oriented statement that describes how we aim to work toward our vision for the world, but is less detail oriented ("content-addressed p2p web") and more outcome oriented ("resilient network to preserve humanity's knowledge").

## Questions for you
- What mission statements inspire you the most from other companies/organizations who think long-term?
- What words or parts of the current mission statement resonate with you?
- What other words or phrases seem especially core to the IPFS project and should be reflected in our mission?
- Do you have any alternate mission statements for the project that resonate?

We plan to synthesize these suggestions to help us refine and improve towards a "Mission 2.0" 
 that we hope to release in Q1. Thanks for your help!

**Comment by momack2** [comment]
My current favorite alternative: 

> _"The mission of IPFS is to create a resilient, upgradable, open network to preserve and grow humanity’s knowledge."_

I'm sure we can do even better!

**Comment by ghostfire51** [comment]
We record everything, we keep everything, so that the future will tell us the truth.

**Comment by liyunzhi-666** [comment]
I think the task of IPFS is to create an inclusive network, both protocol and content. We believe that there is the key to the truth of the world in the knowledge generated from different perspectives and interests.

**Comment by bertrandfalguiere** [comment]
We want to make data, information, and knowledge liquid, for them to reach everywhere they're useful, without friction, whatever the shape they will need to take in the future.

**Comment by metagates-dev** [comment]
Alexandria library online forever

**Comment by autonome** [comment]
Mission statement mood board:

* [IPFS mission statement](https://github.com/ipfs/roadmap#ipfs-mission-statement)
* [Protocol Labs mission statement](https://protocol.ai/) (scroll down, is first bit)
* [Internet Archive mission](https://archive.org/about/)
* Mozilla [mission](https://www.mozilla.org/en-US/mission/) and [manifesto](https://www.mozilla.org/en-US/about/manifesto/)
* W3C TAG's (Technical Architecture Group) guiding document: [Ethical Web Principles](https://w3ctag.github.io/ethical-web-principles/)
* Internet Architecture Board's wip guiding document: [The Internet is for End Users](https://tools.ietf.org/html/draft-iab-for-the-users-01)
* [UK Govt open standards principles](https://www.gov.uk/government/publications/open-standards-principles/open-standards-principles#Defining-open-standards)

**Comment by momack2** [comment]
"Provide Universal Access to All Knowledge" - that's pretty sweet (from Internet Archive). 

I'm going to start trying out the mission in https://github.com/ipfs/roadmap/issues/52#issuecomment-560050964 and see how it feels, with the opportunity to tweak and improve as we go. Would love to find a way to work in our goal to make the web _accessible_ - especially to disconnected or distant users!
