### ISSUE TITLE
[2020 Theme Proposal] Compile go-ipfs to wasm

### ISSUE THREAD

**Issue by NatoBoram** [ipfs/roadmap#57]
_Note, this is part of the [2020 Theme Proposals Process](https://github.com/ipfs/roadmap/blob/master/2020-IPFS-Project-Planning.md) - feel free to create additional/alternate proposals, or discuss this one in the comments!_

## Theme description

> WebAssembly (abbreviated *Wasm*) is a binary instruction format for a stack-based virtual machine. Wasm is designed as a portable target for compilation of high-level languages like C/C++/Rust, enabling deployment on the web for client and server applications.

## Core needs & gaps

While having multiple concurring implementations of the same thing is great, it would be even better if they didn't have to be coded twice. Moreover, some of the benefits of writing the reference implementation in Go are gone if it's going to be completely re-written in JavaScript.

## Why focus this year

There's already considerations of re-writing the whole thing in Rust (#54) because of the disadvantages of maintaining two separate implementations. Focusing efforts on the Go implementation would take less time and bring the same benefits as re-writing it in Rust, namely reduce implementation, maintenance and quality control efforts.

## Milestones & rough roadmap

* Compile `go-ipfs` to `wasm` (https://github.com/ipfs/go-ipfs/issues/5694)
* Reduce its size to a manageable size (https://github.com/ipfs/go-ipfs/pull/5878)
* Change JS-IPFS to be a wrapper around `ipfs.wasm`

## Desired / expected impact

* Faster development cycles for JS-IPFS
* Almost no efforts are required to maintain JS-IPFS
* Better performance for JS-IPFS
* Better reliability for JS-IPFS
* Better portability of Go-IPFS

**Comment by momack2** [comment]
Hey Nato! Are you interested in taking this on? We actually already chose our focus for 2020 (Content Routing Performance), but that doesn't mean this can't move forward. There's active work underway on Rust-IPFS and I'd love to see the wasm prototype graduate into a more serious browser contender as well. If you have some cycles to spend on this that'd be awesome!

**Comment by NatoBoram** [comment]
I would be, but I entered a crunch time at work so I won't have time anytime soon
