### ISSUE TITLE
[2021 Theme Proposal] Codify & Streamline InterPlanetary Stack

### ISSUE THREAD

**Issue by dchoi27** [ipfs/roadmap#61]
_Note, this is part of the [2021 IPFS project planning process ](https://github.com/ipfs/roadmap/blob/master/2021-IPFS-Project-Planning.md) - feel free to add other potential 2021 themes for the IPFS project by opening a [new issue](https://github.com/ipfs/roadmap/issues/new/choose) or discuss this proposed theme in the comments, especially other example workstreams that could fit under this theme for 2021. Please also review others’ proposed themes and leave feedback [here](https://github.com/ipfs/roadmap/labels/2021%20Theme%20Proposal)!_
## Theme description
Codify and smooth the end-to-end adoption pathways and core value propositions of the InterPlanetary Stack. Currently, the pathways for onboarding on IPFS and using it extensibly along with IPLD/libp2p/Filecoin can be unclear to those new to the ecosystem, and clarifying these could unlock new or deeper adoption.

## Hypothesis
A major blocker for large-scale InterPlanetary Stack adoption in Web3 and beyond is clarification of why and how to use IPFS - and how the InterPlanetary stack fits together to solve real-world problems for potential adopters, especially to those new to the ecosystem.

## Vision statement
In defining the core value propositions and usage patterns for the InterPlanetary stack, we help increase alignment across the project’s efforts and opened up new/deeper utility for the project. New ecosystem members clearly understand the project’s value proposition on data accessibility / portability / extensibility and how they can use IPFS effectively in concert with other protocols to achieve their goals. 

## Why focus this year
In 2020 we solidified some critical components of IPFS functionality - like improving content routing performance. As the project matures, it is important to proactively define and center the adoption journey around the core value propositions of IPFS to effectively align the project’s efforts and enable new ecosystem members to grok IPFS’s value proposition to drive project success.

## Example workstreams
Codify canonical IPFS core value proposition, create maintained IPFS spec, articulate adoption pathways for specific use cases, smooth cross-protocol adoption journey, create multi-year upgrade roadmap, improve website and docs to reflect adoption story

**Comment by jessicaschilling** [comment]
Adding some context as what I'd believe would be a further weight in favor of this goal: A lot of this work has been under active discussion for a while, as well as some initial planning, but the 2020 work mentioned above on content routing performance (and some other critical initiatives) left us without the bandwidth required to really throw our full weight behind this as a 2020 goal.

Keeping our 2021 scaling ambitions for the network as a whole in mind, this is a critical time for this goal — plus we've already done a lot of the ground work in researching audiences, personae, goals, etc.

**Comment by melroy89** [comment]
What do you mean with Codify? This issue seems a bit vague to me, and therefor maybe to others as well. Can you be more explicit.
