### ISSUE TITLE
[2021 Theme Proposal] Increase max block size / defualt to blake2b-256

### ISSUE THREAD

**Issue by lizelive** [ipfs/roadmap#73]
_Note, this is part of the [2021 IPFS project planning process ](https://github.com/ipfs/roadmap/blob/master/2021-IPFS-Project-Planning.md) - feel free to add other potential 2021 themes for the IPFS project by opening a [new issue](https://github.com/ipfs/roadmap/issues/new/choose) or discuss this proposed theme in the comments, especially other example workstreams that could fit under this theme for 2021. Please also review others’ proposed themes and leave feedback [here](https://github.com/ipfs/roadmap/labels/2021%20Theme%20Proposal)!_
## Theme description
One thing that limits IPFS usage for large datasets is its very small block size. 256kb is too small, and the largest size (at least for files) is 1mb. For better disk performance a minimum of 4mb would be needed. This will also drastically improve performance when using cloud backings for data storage.

## Hypothesis
Large datasets for repeatable research are a pain to move around, ipfs can fix this.

## Vision statement
allow bitswap to handel 4mb files.

## Why focus this year
The useage is growing and moving to a 4mb default will result in a 16x reduction in overhead. Also makes it performant to use hdd as backing.

## Example workstreams
_Please list relevant workstreams, development milestones, and a high-level timeline for these efforts._

## Other content
_Please include links to other relevant content, notes, etc._

**Comment by atopal** [comment]
Hi @lizelive 

Thank you for this. It looks like your submission might be a possible solution for issue #69 (Scalability) and not a theme in itself. I'm going to close this issue, but can you please comment on that issue with your input?
