### ISSUE TITLE
[2021 Theme Proposal] Integration of the cluster follower into the WebUI 

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/roadmap#85]
_Note, this is part of the [2021 IPFS project planning process ](https://github.com/ipfs/roadmap/blob/master/2021-IPFS-Project-Planning.md) - feel free to add other potential 2021 themes for the IPFS project by opening a [new issue](https://github.com/ipfs/roadmap/issues/new/choose) or discuss this proposed theme in the comments, especially other example workstreams that could fit under this theme for 2021. Please also review others’ proposed themes and leave feedback [here](https://github.com/ipfs/roadmap/labels/2021%20Theme%20Proposal)!_
## Theme description
Currently it's hard for new users to find data to store on their nodes. I often recommended the websites and new users were surprised to hear that there's a cluster-implementation based on ipfs. 

## Hypothesis
I feel like we should make the collaborative clusters much more visible, by integrating a join/leave functionality into the WebUI. 

It would be nice to hide the technicalities behind a link, like that there's a toolkit and the specific addresses etc. 

It's more interesting to show the users a link to the cluster pinset, so they can see what they will share with the network and group the pins of each cluster the user is taking part in the WebUI to see how much storage each cluster uses. 

## Vision statement
A join should start a progress bar, where the number of pins processed/remaining are showed and how much storage in total a cluster stores on the node. 

This allows the users to take part from right after firing their node up the first time and show what interesting kinds of data are stored on the filesystem, encouraging them to browse the filesystem for a while. 

Additionally stats like how many nodes take part in the cluster would be interesting to show there, encouraging the user to select a cluster which might have a lower amount of participants over larger ones. 

## Why focus this year
Last year the IPFS-team put collaborative clusters and we found some exiting ways to use them. Now it's time to make them more visible and easier to handle by new users to bring them to a broader audience and enhance the 'new user' experience. 

## Example realization 

We could replace the explore tab which currently lists like 3 or 4 static cids which are interesting but not really dynamic.

Instead we could load latest collaborative cluster list (via IPNS) in a bit more new user friendly explanations and descriptions provided by the cluster administrators in somethings like a simple yaml. 

This gets parsed and rendered in the tab. The cluster node which allows us to join is then asked for the amount of nodes in the cluster and the current size of the cluster-pinset and a CID to the cluster-pinset. (Not sure if that's currently available via the API but it should be a minor addition). 

Then we present this to the user, which can then press join and the node starts running a cluster follower in the background as long at its running.

**Comment by jessicaschilling** [comment]
Cross-referencing existing https://github.com/ipfs/ipfs-gui/issues/59.

**Comment by RubenKelevra** [comment]
@2color do I now have to bump my roadmap proposals once a month to keep them open, or what's the idea here?
